[package]
name = "asiba-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
asiba-core.workspace = true
asiba-transport.workspace = true
asiba-config.workspace = true
asiba-storage.workspace = true
asiba-docgen.workspace = true
asiba-alerts.workspace = true
asiba-incidents.workspace = true
asiba-modules.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
ureq.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
