mod files;
mod modules;
mod pipelines;
mod settings;

pub use files::*;
pub use modules::*;
pub use pipelines::*;
pub use settings::*;

pub const APP_NAME: &str = "SIB";

pub const NAV_OVERVIEW: &str = "Overview";
pub const NAV_SERVERS: &str = "Servers";
pub const NAV_ALERTS: &str = "Alerts";
pub const NAV_MAP: &str = "Map";
pub const NAV_SETTINGS: &str = "Settings";

pub const STATUS_ONLINE: &str = "online";
pub const STATUS_OFFLINE: &str = "offline";
pub const STATUS_CONNECTING: &str = "connecting";
pub const STATUS_UNTRUSTED: &str = "host key";
pub const STATUS_LIVE: &str = "updated";
pub const STATUS_PAUSED: &str = "paused";
pub const BTN_PAUSE: &str = "⏸";
pub const BTN_RESUME: &str = "▶";
pub const STATUS_ATTACK: &str = "ATTACK";

pub const OVERVIEW_TITLE: &str = "Overview";
pub const TILE_SERVERS: &str = "Servers";
pub const TILE_ONLINE: &str = "Online";
pub const TILE_OFFLINE: &str = "Offline";
pub const TILE_CPU: &str = "CPU avg";
pub const TILE_MEMORY: &str = "RAM avg";
pub const TILE_DISK: &str = "Disk avg";
pub const TILE_TRAFFIC: &str = "Traffic";
pub const SECTION_EVENTS: &str = "Recent events";
pub const SECTION_DEPLOYS: &str = "Deploys running now";
pub const SECTION_ANOMALIES: &str = "Anomalies";
pub const SECTION_INCIDENTS: &str = "Incidents";
pub const INCIDENT_NOTICE: &str = "incident";
pub const INCIDENT_OPEN_HINT: &str = "open the section with the details";
pub const INCIDENT_IGNORE: &str = "archive";
pub const INCIDENT_IGNORE_HINT: &str = "Move to the archive: an incident of this kind on this server will not open, will not raise alerts and will not show up in lists. Bring it back on the Alerts page.";
pub const INCIDENTS_ARCHIVE: &str = "Incident archive";
pub const INCIDENTS_ARCHIVE_EMPTY: &str = "the archive is empty";
pub const INCIDENT_RESTORE: &str = "restore";
pub const INCIDENT_ALERT: &str = "alert";
pub const INCIDENT_ANOMALY: &str = "anomaly";
pub const INCIDENT_BRUTE_FORCE: &str = "brute force";
pub const INCIDENT_SECURITY: &str = "security";
pub const INCIDENT_UNIT: &str = "unit failed";
pub const INCIDENT_CONTAINER: &str = "container";
pub const INCIDENT_DEPLOY: &str = "deploy failed";
pub const INCIDENT_DISK: &str = "disk";
pub const INCIDENT_MEMORY: &str = "memory";
pub const INCIDENT_UPDATES: &str = "updates";
pub const INCIDENT_MODULE: &str = "data collection";
pub const INCIDENT_CLOCK: &str = "clock";
pub const SECTION_TOP: &str = "Busiest servers";
pub const TILE_ALERTS: &str = "Alerts";
pub const TILE_DISK_SHORT: &str = "Disk";
pub const EVENTS_LEVEL: &str = "level from";
pub const COL_ALERTS: &str = "Alerts";
pub const SECTION_SERVERS: &str = "Servers";
pub const EMPTY_EVENTS: &str = "No events yet";
pub const EMPTY_SERVERS: &str = "No servers. Add one.";

pub const SERVERS_TITLE: &str = "Servers";
pub const SERVERS_SEARCH: &str = "search: name, host, project, tag";
pub const SERVERS_NO_MATCH: &str = "nothing found";
pub const FILTER_ALL: &str = "all";
pub const FILTER_PROBLEMS: &str = "with problems";
pub const VIEW_GRID: &str = "grid";
pub const VIEW_TABLE: &str = "table";
pub const FORM_TAGS_SHORT: &str = "Tags";
pub const BTN_ADD_SERVER: &str = "+ Add server";
pub const BTN_EDIT: &str = "Edit";
pub const BTN_RECONNECT: &str = "Reconnect";
pub const BTN_DELETE: &str = "Delete";
pub const BTN_BACK: &str = "< Back";
pub const BTN_SAVE: &str = "Save";
pub const BTN_CANCEL: &str = "Cancel";
pub const BTN_TEST: &str = "Test the connection";
pub const BTN_TRUST_KEY: &str = "Trust the key and retry";
pub const BTN_TRUST_KEY_SERVER: &str = "Trust the key";
pub const BTN_CONFIRM_DELETE: &str = "Delete for good";
pub const BTN_CLOSE: &str = "Close";
pub const BLOCK_SETTINGS: &str = "Block settings";
pub const BTN_SERVER_FILE: &str = "File";
pub const BTN_TERMINAL: &str = "Terminal";
pub const BTN_TERMINAL_SHORT: &str = ">_";
pub const BTN_TERMINAL_HINT: &str = "open SSH in a terminal";
pub const ERR_NO_TERMINAL: &str = "no terminal emulator found (set $TERMINAL)";
pub const ERR_OPEN_FAILED: &str = "could not open";
pub const ERR_AI_KEY_NOT_STORED: &str = "the AI key was not saved to the keyring";
pub const INSPECTOR_TITLE: &str = "Viewer";
pub const INSPECTOR_LOADING: &str = "Loading...";

pub const FORM_TITLE_ADD: &str = "New server";
pub const FORM_TITLE_EDIT: &str = "Edit server";
pub const FORM_SECTION_CONNECTION: &str = "Connection";
pub const FORM_SECTION_AUTH: &str = "Login";
pub const FORM_SECTION_JUMP: &str = "Jump host";
pub const FORM_SECTION_SUDO: &str = "sudo";
pub const FORM_SECTION_DESCRIPTION: &str = "Description";
pub const FORM_SECTION_TEST: &str = "Test";
pub const FORM_NAME: &str = "Name";
pub const FORM_NAME_HINT: &str = "lowercase latin letters, digits, hyphen";
pub const FORM_HOST: &str = "Host";
pub const FORM_PORT: &str = "Port";
pub const FORM_USER: &str = "User";
pub const FORM_AUTH_AUTO: &str = "Auto (ssh-agent, ~/.ssh/id_*)";
pub const FORM_AUTH_KEY: &str = "Private key";
pub const FORM_AUTH_PASSWORD: &str = "Password";
pub const FORM_KEY_PATH: &str = "Path to the key";
pub const FORM_PASSPHRASE: &str = "Passphrase";
pub const FORM_PASSWORD: &str = "Password";
pub const FORM_JUMP_ENABLE: &str = "Connect through a jump server";
pub const FORM_SUDO_NONE: &str = "No sudo";
pub const FORM_SUDO_PASSWORDLESS: &str = "sudo without a password";
pub const FORM_SUDO_PASSWORD: &str = "sudo with a password";
pub const FORM_SUDO_PASSWORD_FIELD: &str = "sudo password";
pub const FORM_PROJECT: &str = "Project";
pub const FORM_PURPOSE: &str = "Purpose";
pub const FORM_ENVIRONMENT: &str = "Environment";
pub const FORM_TAGS: &str = "Tags (comma separated)";
pub const FORM_OWNER: &str = "Owner";
pub const FORM_LINKS: &str = "Links (one per line)";
pub const FORM_NOTES: &str = "Notes";
pub const FORM_LOCATION: &str = "Coordinates";
pub const FORM_LOCATION_HINT: &str = "empty means by IP, otherwise 52.52, 13.40";
pub const FORM_LOCATION_LABEL: &str = "Place";
pub const FORM_SECRETS_KEPT: &str = "empty keeps the saved one";

pub const ENV_PRODUCTION: &str = "production";
pub const ENV_STAGING: &str = "staging";
pub const ENV_DEVELOPMENT: &str = "development";
pub const ENV_OTHER: &str = "other";

pub const TEST_IDLE: &str = "The connection has not been tested yet";
pub const TEST_RUNNING: &str = "Connecting...";
pub const TEST_OK: &str = "Connected";
pub const TEST_FAILED: &str = "Error";
pub const TEST_MODULES: &str = "Modules";
pub const TEST_UNKNOWN_KEY: &str = "This host key is new. Fingerprint:";
pub const TEST_CHANGED_KEY: &str =
    "The host key changed. The server may have been swapped. Fingerprint:";

pub const AVAIL_AVAILABLE: &str = "available";
pub const AVAIL_PARTIAL: &str = "partial";
pub const AVAIL_UNAVAILABLE: &str = "unavailable";

pub const DETAIL_SECTION_CONNECTION: &str = "Connection";
pub const DETAIL_OPEN: &str = "open >";
pub const DETAIL_SECTION_MODULES: &str = "Modules";
pub const DETAIL_SECTION_DESCRIPTION: &str = "Description";
pub const DETAIL_RETRY_AT: &str = "retry in";
pub const DETAIL_ONLINE_SINCE: &str = "online since";
pub const DETAIL_NO_DATA: &str = "no data yet";
pub const DETAIL_DELETE_PROMPT: &str = "Type the server name to confirm:";

pub const COL_MODULE: &str = "Module";
pub const COL_STATUS: &str = "Status";
pub const COL_UPDATED: &str = "Updated";
pub const COL_ERROR: &str = "Error";
pub const COL_NAME: &str = "Name";
pub const COL_HOST: &str = "Host";
pub const COL_OS: &str = "OS";
pub const COL_UPTIME: &str = "Uptime";
pub const COL_TIME: &str = "Time";
pub const COL_SERVER: &str = "Server";
pub const COL_MESSAGE: &str = "Message";
pub const COL_SEVERITY: &str = "Level";

pub const ALERTS_TITLE: &str = "Alerts";
pub const ALERTS_ACTIVE: &str = "Active";
pub const ALERTS_HISTORY: &str = "History";
pub const ALERTS_NONE_ACTIVE: &str = "no active alerts";
pub const ALERTS_NONE_HISTORY: &str = "the history is empty";
pub const ALERTS_RULE: &str = "Rule";
pub const ALERTS_OPEN_HINT: &str = "open the server section with the details";
pub const ALERTS_VALUE: &str = "Value";
pub const ALERTS_STARTED: &str = "Started";
pub const ALERTS_DURATION: &str = "Duration";
pub const ALERTS_ACK: &str = "acknowledge";
pub const ALERTS_ACKED: &str = "acknowledged";
pub const ALERTS_MUTE_1H: &str = "mute 1h";
pub const ALERTS_MUTE_24H: &str = "24h";
pub const ALERTS_MUTED: &str = "muted until";
pub const SETTINGS_SECTION_ALERTS: &str = "Alert rules";
pub const SETTINGS_NOTIFICATIONS: &str = "Desktop notifications (warning and critical)";
pub const RULE_NAME: &str = "Name";
pub const RULE_METRIC: &str = "Metric";
pub const RULE_CONDITION: &str = "Condition";
pub const RULE_THRESHOLD: &str = "Threshold";
pub const RULE_FOR: &str = "For, s";
pub const RULE_SEVERITY: &str = "Level";
pub const RULE_ADD: &str = "Add rule";
pub const RULE_REMOVE: &str = "delete";
pub const RULE_RESET: &str = "reset";
pub const RULE_ENABLED: &str = "On";
pub const RULE_INCOMPLETE: &str = "every rule needs a name and a metric";
pub const RULE_HINT: &str = "The metric is a series key, for example cpu.total, memory.used_pct, disk.fs./.used_pct, network.rx_bps, ping.rtt_ms.";
pub const SEVERITY_INFO: &str = "info";
pub const SEVERITY_WARNING: &str = "warning";
pub const SEVERITY_CRITICAL: &str = "critical";
pub const MAP_TITLE: &str = "Map";
pub const MAP_EMPTY: &str = "No servers have coordinates: geolocation failed or is turned off.";
pub const MAP_LEGEND_HOME: &str = "this machine";
pub const SECTION_MAP: &str = "Map";
pub const DETAIL_LOCATION: &str = "location";
pub const DETAIL_LOCATION_MANUAL: &str = "set by hand";
pub const DETAIL_LOCATION_PENDING: &str = "resolving...";
