[package]
name = "asiba-modules"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
asiba-core.workspace = true
async-trait.workspace = true
chrono.workspace = true
thiserror.workspace = true

[dev-dependencies]
asiba-transport.workspace = true
tokio.workspace = true

[lints]
workspace = true
