[package]
name = "asiba-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "asiba"
path = "src/main.rs"

[dependencies]
asiba-core.workspace = true
asiba-config.workspace = true
asiba-engine.workspace = true
asiba-llm.workspace = true
asiba-modules.workspace = true
asiba-storage.workspace = true
asiba-ui.workspace = true
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
